#!/bin/sh

# Set these paths appropriately

BIN="/home/brian/people/Petra/NEReus/treetagger/bin"
CMD="/home/brian/people/Petra/NEReus/treetagger/cmd"
LIB="/home/brian/people/Petra/NEReus/treetagger/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/dutch-abbreviations
PARFILE=${LIB}/dutch.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
