#!/bin/sh

# Set these paths appropriately

BIN="/home/brian/people/Petra/NEReus/treetagger/bin"
CMD="/home/brian/people/Petra/NEReus/treetagger/cmd"
LIB="/home/brian/people/Petra/NEReus/treetagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/persian.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
