#!/bin/sh

# Set these paths appropriately

BIN="/home/brian/people/Petra/NEReus/treetagger/bin"
CMD="/home/brian/people/Petra/NEReus/treetagger/cmd"
LIB="/home/brian/people/Petra/NEReus/treetagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/romanian-abbreviations
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/romanian.par

$TOKENIZER -r -a $ABBR_LIST $* |
${CMD}/split-romanian.perl ${LIB}/romanian-tokens |
$TAGGER $OPTIONS $PARFILE
